In [1]:
pip install ifcopenshell

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [15]:
import ifcopenshell

# Load an IFC file
file_path = './AC20-FZK-Haus.ifc'
ifc_model = ifcopenshell.open(file_path)
print(ifc_model.schema)

IFC4


In [16]:
print(ifc_model.by_id(1))

#1=IfcPerson($,'Nicht definiert',$,$,$,$,$,$)


In [17]:
import ifcopenshell.util.placement

wall = ifc_model.by_type("IfcWall")[0]
# This returns a 4x4 matrix, including the location and rotation. For example:
# array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00, 2.00000000e+00],
#        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00, 3.00000000e+00],
#        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00, 5.00000000e+00],
#        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 1.00000000e+00]])
matrix = ifcopenshell.util.placement.get_local_placement(wall.ObjectPlacement)
# The last column holds the XYZ values, such as:
# array([ 2.00000000e+00,  3.00000000e+00,  5.00000000e+00])
print(matrix)
print(matrix[:,3][:3])

[[1.   0.   0.   7.41]
 [0.   1.   0.   4.25]
 [0.   0.   1.   0.  ]
 [0.   0.   0.   1.  ]]
[7.41 4.25 0.  ]


In [6]:
walls = ifc_model.by_type('IfcWall')
print(len(walls))

13


In [7]:
wall=walls[0]
print(wall)
print(wall.is_a('IfcWall')) # Returns True
print(wall.is_a('IfcElement')) # Returns True
print(wall.is_a('IfcWindow')) # Returns False
print(wall[0])
print(wall.GlobalId)
print(wall.Name)

#15042=IfcWallStandardCase('2XPyKWY018sA1ygZKgQPtU',#12,'Wand-Int-ERDG-4',$,$,#14983,#15037,'BC6F0F70-6195-495E-A2-FC-239713029DB1',$)
True
True
False
2XPyKWY018sA1ygZKgQPtU
2XPyKWY018sA1ygZKgQPtU
Wand-Int-ERDG-4


In [8]:
print(ifc_model.by_id(12))
print(ifc_model.by_id(432))
print(ifc_model.by_id(476))
print(ifc_model.by_id(477))
print(ifc_model.by_id(14980))
print(ifc_model.by_id(14976))
print(ifc_model.by_id(14978))
print(ifc_model.by_id(14982))
print(ifc_model.by_id(14983))
print(ifc_model.by_id(15016))
print(ifc_model.by_id(15024))
print(ifc_model.by_id(15033))
print(ifc_model.by_id(15037))
print(ifc_model.by_id(15042))

#12=IfcOwnerHistory(#7,#11,$,.ADDED.,$,$,$,1482339244)
#432=IfcLocalPlacement(#115,#431)
#476=IfcAxis2Placement3D(#474,#472,#470)
#477=IfcLocalPlacement(#432,#476)
#14980=IfcCartesianPoint((7.41,4.25,0.))
#14976=IfcDirection((1.,0.,0.))
#14978=IfcDirection((0.,0.,1.))
#14982=IfcAxis2Placement3D(#14980,#14978,#14976)
#14983=IfcLocalPlacement(#477,#14982)
#15016=IfcShapeRepresentation(#118,'Body','SweptSolid',(#15006))
#15024=IfcShapeRepresentation(#375,'Box','BoundingBox',(#15023))
#15033=IfcShapeRepresentation(#15026,'Axis','Curve2D',(#15031))
#15037=IfcProductDefinitionShape($,$,(#15016,#15024,#15033))
#15042=IfcWallStandardCase('2XPyKWY018sA1ygZKgQPtU',#12,'Wand-Int-ERDG-4',$,$,#14983,#15037,'BC6F0F70-6195-495E-A2-FC-239713029DB1',$)


In [9]:
print(type(ifc_model.by_id(15042)))
print(len(dir(ifc_model.by_id(15042))))
print(dir(ifc_model.by_id(15042)))
ifc_model.by_id(15042)


<class 'ifcopenshell.entity_instance.entity_instance'>
83
['ConnectedFrom', 'ConnectedTo', 'ContainedInStructure', 'Declares', 'Decomposes', 'Description', 'FillsVoids', 'GlobalId', 'HasAssignments', 'HasAssociations', 'HasContext', 'HasCoverings', 'HasOpenings', 'HasProjections', 'InterferesElements', 'IsConnectionRealization', 'IsDeclaredBy', 'IsDecomposedBy', 'IsDefinedBy', 'IsInterferedByElements', 'IsNestedBy', 'IsTypedBy', 'Name', 'Nests', 'ObjectPlacement', 'ObjectType', 'OwnerHistory', 'PredefinedType', 'ProvidesBoundaries', 'ReferencedBy', 'ReferencedInStructures', 'Representation', 'Tag', '__annotations__', '__class__', '__del__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rge__', '__rgt__', '__rle__', '__rl

#15042=IfcWallStandardCase('2XPyKWY018sA1ygZKgQPtU',#12,'Wand-Int-ERDG-4',$,$,#14983,#15037,'BC6F0F70-6195-495E-A2-FC-239713029DB1',$)

In [10]:
import ifcopenshell.util
import ifcopenshell.util.element
#print(ifcopenshell.util.element.get_psets(wall))

In [11]:
# Create a set to store unique entity types
entity_types = set()
# Iterate through all entities in the model and collect their types
for entity in ifc_model:
    entity_types.add(entity.is_a())

print(sorted(entity_types)[:7])
# Print all unique entity types
for entity_type in sorted(entity_types)[:10]:
    print(entity_type)

['IfcAnnotation', 'IfcApplication', 'IfcArbitraryClosedProfileDef', 'IfcAxis2Placement2D', 'IfcAxis2Placement3D', 'IfcBeam', 'IfcBeamType']
IfcAnnotation
IfcApplication
IfcArbitraryClosedProfileDef
IfcAxis2Placement2D
IfcAxis2Placement3D
IfcBeam
IfcBeamType
IfcBooleanClippingResult
IfcBoundingBox
IfcBuilding


In [63]:
len(entity_types)

115

In [75]:
# Print all unique entity types
total = 0
size_set = set()
for entity_type in sorted(entity_types):
    print(entity_type + " " + str(len(ifc_model.by_type(entity_type))))
    total += len(ifc_model.by_type(entity_type))
    for i in ifc_model.by_type(entity_type):
        size_set.add(len(i.__dict__))

IfcAnnotation 14
IfcApplication 1
IfcArbitraryClosedProfileDef 22
IfcAxis2Placement2D 94
IfcAxis2Placement3D 364
IfcBeam 4
IfcBeamType 2
IfcBooleanClippingResult 6
IfcBoundingBox 107
IfcBuilding 1
IfcBuildingStorey 2
IfcCartesianPoint 11359
IfcCartesianTransformationOperator3D 56
IfcClassificationReference 1
IfcClosedShell 140
IfcColourRgb 12
IfcCompositeCurve 81
IfcCompositeCurveSegment 81
IfcConnectionSurfaceGeometry 81
IfcConversionBasedUnit 1
IfcCurveBoundedPlane 81
IfcCurveStyle 4
IfcCurveStyleFont 1
IfcCurveStyleFontPattern 1
IfcDerivedUnit 3
IfcDerivedUnitElement 8
IfcDimensionalExponents 1
IfcDirection 875
IfcDoor 5
IfcDoorLiningProperties 4
IfcDoorPanelProperties 5
IfcDoorType 5
IfcDraughtingPreDefinedColour 2
IfcDraughtingPreDefinedCurveFont 3
IfcElementQuantity 176
IfcExtrudedAreaSolid 51
IfcFace 6406
IfcFaceBound 6452
IfcFaceOuterBound 6406
IfcFacetedBrep 140
IfcGeometricCurveSet 235
IfcGeometricRepresentationContext 7
IfcGeometricRepresentationSubContext 5
IfcHalfSpaceSoli

In [76]:
size_set

{3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 19}

In [ ]:
for en
walls = ifc_model.by_type('IfcWall')
print(len(walls))

In [44]:
# Get all entities in the model
all_entities = ifc_model.by_type("IfcProduct")  # Or use "IfcRoot" for broader counting

# Print the number of entities
print("Number of entities:", len(all_entities))

Number of entities: 127


In [45]:
all_entities

[#15372=IfcAnnotation('2TSghi3E94BuNE_F6jBcWe',#12,$,$,$,#15264,#15369),
 #15848=IfcAnnotation('0j7WClqLTB0gkHE605BLnY',#12,$,$,$,#15384,#15845),
 #16507=IfcAnnotation('3BTqRqk7D5EhoEfLy$YPgs',#12,$,$,$,#15859,#16504),
 #16982=IfcAnnotation('11pyNSTMP9zfUCy679gsvT',#12,$,$,$,#16518,#16979),
 #18407=IfcAnnotation('3YZcx3Gb58SwNRLuheFOxL',#12,$,$,$,#17759,#18404),
 #20069=IfcAnnotation('0dGzbiP6H1sPcT0NmqaFGO',#12,$,$,$,#19789,#20066),
 #20268=IfcAnnotation('2Ml9lHXiTBN8zH$beU1ns5',#12,$,$,$,#20080,#20265),
 #20299=IfcAnnotation('2HtybvLgf93veGIhadqbJ9',#12,$,$,$,#20279,#20296),
 #20329=IfcAnnotation('1WAtLpg_nDBxKhzIXT_jnH',#12,$,$,$,#20310,#20326),
 #20808=IfcAnnotation('1TKECZOIj9cBBj4ne6lhuA',#12,$,$,$,#20784,#20805),
 #33672=IfcAnnotation('0CWpGkM7zEROS7WsgthNfA',#12,$,$,$,#33651,#33669),
 #35053=IfcAnnotation('1fzvgX3pDB88Tz63VWPBLu',#12,$,$,$,#35036,#35050),
 #75775=IfcAnnotation('2BEAsxujfCOxQo3wTVr7Wr',#12,$,$,$,#75541,#75772),
 #76112=IfcAnnotation('0OL3LCjon8C8eMGVs718Tk',#12,

In [53]:
import ifcopenshell
from ifcopenshell.geom import create_shape
from ifcopenshell import util

# Load the IFC model
#ifc_model = ifcopenshell.open('path/to/your/file.ifc')

# Set up geometry settings
settings = ifcopenshell.geom.settings()

# Function to get the location of an object (position and orientation)
def get_location(entity):
    # Check if the entity has a Local Placement
    if entity.is_a('IfcProduct'):
        placement = entity.ObjectPlacement
        if placement and placement.is_a('IfcLocalPlacement'):
            # Extract the location (position) and orientation (rotation)
            placement_location = placement.RelativePlacement.Location
            return placement_location
    return None

# Function to extract geometry and location for each product (object)
for entity in ifc_model.by_type('IfcProduct'):
    try:
        # Get the geometry for the product (e.g., wall, door, etc.)
        shape = create_shape(settings, entity)
        geometry = shape.geometry
        
        # Get the location of the entity
        location = get_location(entity)

        # Print geometry and location information (for debugging or processing)
        print(f"Entity: {entity}")
        print(f"Geometry: {geometry}")  # This will be the raw geometry data (can be further processed)
        
        if location:
            print(f"Location: {location}")
        else:
            print("No location found.")
        
        print("-" * 50)  # Separator for readability
    except Exception as e:
        print(f"Error processing {entity}: {e}")

Error processing #15372=IfcAnnotation('2TSghi3E94BuNE_F6jBcWe',#12,$,$,$,#15264,#15369): Failed to process shape
Error processing #15848=IfcAnnotation('0j7WClqLTB0gkHE605BLnY',#12,$,$,$,#15384,#15845): Failed to process shape
Error processing #16507=IfcAnnotation('3BTqRqk7D5EhoEfLy$YPgs',#12,$,$,$,#15859,#16504): Failed to process shape
Error processing #16982=IfcAnnotation('11pyNSTMP9zfUCy679gsvT',#12,$,$,$,#16518,#16979): Failed to process shape
Error processing #18407=IfcAnnotation('3YZcx3Gb58SwNRLuheFOxL',#12,$,$,$,#17759,#18404): Failed to process shape
Error processing #20069=IfcAnnotation('0dGzbiP6H1sPcT0NmqaFGO',#12,$,$,$,#19789,#20066): Failed to process shape
Error processing #20268=IfcAnnotation('2Ml9lHXiTBN8zH$beU1ns5',#12,$,$,$,#20080,#20265): Failed to process shape
Error processing #20299=IfcAnnotation('2HtybvLgf93veGIhadqbJ9',#12,$,$,$,#20279,#20296): Failed to process shape
Error processing #20329=IfcAnnotation('1WAtLpg_nDBxKhzIXT_jnH',#12,$,$,$,#20310,#20326): Failed 

In [14]:
# Retrieve the geometry (triangulated mesh) and location for an entity
for entity in ifc_model.by_type('IfcProduct'):
    try:
        # Create shape for the entity
        shape = create_shape(settings, entity)
        geometry = shape.geometry

        # Get location (position)
        location = get_location(entity)
        if location:
            position = location.Coordinates
            print(f"Entity: {entity.GlobalId} Location: {position}")
        
    except Exception as e:
        print(f"Error processing {entity}: {e}")


Error processing #15372=IfcAnnotation('2TSghi3E94BuNE_F6jBcWe',#12,$,$,$,#15264,#15369): name 'create_shape' is not defined
Error processing #15848=IfcAnnotation('0j7WClqLTB0gkHE605BLnY',#12,$,$,$,#15384,#15845): name 'create_shape' is not defined
Error processing #16507=IfcAnnotation('3BTqRqk7D5EhoEfLy$YPgs',#12,$,$,$,#15859,#16504): name 'create_shape' is not defined
Error processing #16982=IfcAnnotation('11pyNSTMP9zfUCy679gsvT',#12,$,$,$,#16518,#16979): name 'create_shape' is not defined
Error processing #18407=IfcAnnotation('3YZcx3Gb58SwNRLuheFOxL',#12,$,$,$,#17759,#18404): name 'create_shape' is not defined
Error processing #20069=IfcAnnotation('0dGzbiP6H1sPcT0NmqaFGO',#12,$,$,$,#19789,#20066): name 'create_shape' is not defined
Error processing #20268=IfcAnnotation('2Ml9lHXiTBN8zH$beU1ns5',#12,$,$,$,#20080,#20265): name 'create_shape' is not defined
Error processing #20299=IfcAnnotation('2HtybvLgf93veGIhadqbJ9',#12,$,$,$,#20279,#20296): name 'create_shape' is not defined
Error pr

In [57]:
# Debugging geometry attributes
print(f"Geometry attributes: {geometry.__dict__}")

Geometry attributes: {'this': <Swig Object of type 'IfcGeom::Representation::Triangulation *' at 0x7ceba53f1f80>}


In [18]:
import ifcopenshell
import ifcopenshell.geom
import ifcopenshell.util.shape

ifc_file = ifcopenshell.open('./AC20-FZK-Haus1.ifc')
element = ifc_file.by_type('IfcWall')[0]

settings = ifcopenshell.geom.settings()
shape = ifcopenshell.geom.create_shape(settings, element)

# The GUID of the element we processed
print("GUID ", shape.guid)

# The ID of the element we processed
print("id ", shape.id)

# The element we are processing
print("Element", ifc_file.by_guid(shape.guid))

# A unique geometry ID, useful to check whether or not two geometries are
# identical for caching and reuse. The naming scheme is:
# IfcShapeRepresentation.id{-layerset-LayerSet.id}{-material-Material.id}{-openings-[Opening n.id ...]}{-world-coords}
print(shape.geometry.id)

# A 4x4 matrix representing the location and rotation of the element, in the form:
# [ [ x_x, y_x, z_x, x   ]
#   [ x_y, y_y, z_y, y   ]
#   [ x_z, y_z, z_z, z   ]
#   [ 0.0, 0.0, 0.0, 1.0 ] ]
# The position is given by the last column: (x, y, z)
# The rotation is described by the first three columns, by explicitly specifying the local X, Y, Z axes.
# The first column is a normalised vector of the local X axis: (x_x, x_y, x_z)
# The second column is a normalised vector of the local Y axis: (y_x, y_y, y_z)
# The third column is a normalised vector of the local Z axis: (z_x, z_y, z_z)
# The axes follow a right-handed coordinate system.
# Objects are never scaled, so the scale factor of the matrix is always 1.
matrix = shape.transformation.matrix

# For convenience, you might want the matrix as a nested numpy array, so you can do matrix math.
matrix = ifcopenshell.util.shape.get_shape_matrix(shape)

# You can also extract the XYZ location of the matrix.
location = matrix[:,3][0:3]

# X Y Z of vertices in flattened list e.g. [v1x, v1y, v1z, v2x, v2y, v2z, ...]
# These vertices are local relative to the shape's transformation matrix.
verts = shape.geometry.verts

# Indices of vertices per edge e.g. [e1v1, e1v2, e2v1, e2v2, ...]
# If the geometry is mesh-like, edges contain the original edges.
# These may be quads or ngons and not necessarily triangles.
edges = shape.geometry.edges

# Indices of vertices per triangle face e.g. [f1v1, f1v2, f1v3, f2v1, f2v2, f2v3, ...]
# Note that faces are always triangles.
faces = shape.geometry.faces

# Since the lists are flattened, you may prefer to group them like so depending on your geometry kernel
# A nested numpy array e.g. [[v1x, v1y, v1z], [v2x, v2y, v2z], ...]
grouped_verts = ifcopenshell.util.shape.get_vertices(shape.geometry)
# A nested numpy array e.g. [[e1v1, e1v2], [e2v1, e2v2], ...]
grouped_edges = ifcopenshell.util.shape.get_edges(shape.geometry)
# A nested numpy array e.g. [[f1v1, f1v2, f1v3], [f2v1, f2v2, f2v3], ...]
grouped_faces = ifcopenshell.util.shape.get_faces(shape.geometry)

# A list of styles that are relevant to this shape
styles = shape.geometry.materials
print(styles)

for style in styles:
    # Each style is named after the entity class if a default
    # material is applied. Otherwise, it is named "surface-style-{SurfaceStyle.name}"
    # All non-alphanumeric characters are replaced with a "-".
    #print(style.original_name())

    # A more human readable name
    #print(style.name)

    # Each style may have diffuse colour RGB codes
    #if style.has_diffuse:
    #    print(style.diffuse)

    # Each style may have transparency data
    if style.has_transparency:
        print(style.transparency)

# Indices of material applied per triangle face e.g. [f1m, f2m, ...]
material_ids = shape.geometry.material_ids

# IDs representation item per triangle face e.g. [f1i, f2i, ...]
item_ids = shape.geometry.item_ids

GUID  2XPyKWY018sA1ygZKgQPtU
id  15042
Element #15042=IfcWallStandardCase('2XPyKWY018sA1ygZKgQPtU',#12,'Wand-Int-ERDG-4',$,$,#14983,#15037,'BC6F0F70-6195-495E-A2-FC-239713029DB1',$)
15016
(style
     name IfcSurfaceStyleRendering-15008
     diffuse
            colour 0.81 0.81 0.81
     specular
             colour 0.09 0.09 0.09
,)
0.0


In [65]:
material_ids

(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)

In [73]:
def print_by_ids(ids):
    for i in ids:
        print(ifc_file.by_id(i))

In [85]:
print(set(item_ids))
print_by_ids([15006,14994,15004,15003,
    15001, 14999, 14997,
    14992,14984,14986,14988,14990,14984])


{15006}
#15006=IfcExtrudedAreaSolid(#14994,#15003,#15004,2.5)
#14994=IfcArbitraryClosedProfileDef(.AREA.,'',#14992)
#15004=IfcDirection((0.,0.,1.))
#15003=IfcAxis2Placement3D(#15001,#14999,#14997)
#15001=IfcCartesianPoint((0.,0.,0.))
#14999=IfcDirection((0.,0.,1.))
#14997=IfcDirection((1.,0.,0.))
#14992=IfcPolyline((#14984,#14986,#14988,#14990,#14984))
#14984=IfcCartesianPoint((0.,-0.24))
#14986=IfcCartesianPoint((4.29,-0.24))
#14988=IfcCartesianPoint((4.29,0.))
#14990=IfcCartesianPoint((0.24,0.))
#14984=IfcCartesianPoint((0.,-0.24))
