In [1]:
pip install ifcopenshell

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import ifcopenshell

# Load an IFC file
file_path = 'DummyModel.ifc'
ifc_model = ifcopenshell.open(file_path)
print(ifc_model.schema)

IFC2X3


In [3]:
print(ifc_model.by_id(1))

#1=IfcPerson('PEIKKO\pillisam','Undefined',$,$,$,$,$,$)


In [8]:
import ifcopenshell.util.placement

wall = ifc_model.by_type("IfcColumn")[0]
# This returns a 4x4 matrix, including the location and rotation. For example:
# array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00, 2.00000000e+00],
#        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00, 3.00000000e+00],
#        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00, 5.00000000e+00],
#        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 1.00000000e+00]])
matrix = ifcopenshell.util.placement.get_local_placement(wall.ObjectPlacement)
# The last column holds the XYZ values, such as:
# array([ 2.00000000e+00,  3.00000000e+00,  5.00000000e+00])
print(matrix)
print(matrix[:,3][:3])

[[0.0e+00 1.0e+00 0.0e+00 3.6e+04]
 [0.0e+00 0.0e+00 1.0e+00 0.0e+00]
 [1.0e+00 0.0e+00 0.0e+00 0.0e+00]
 [0.0e+00 0.0e+00 0.0e+00 1.0e+00]]
[36000.     0.     0.]


In [9]:
walls = ifc_model.by_type('IfcColumn')
print(len(walls))

28


In [19]:
import ifcopenshell.util
import ifcopenshell.util.element
#print(ifcopenshell.util.element.get_psets(wall))

In [21]:
# Create a set to store unique entity types
entity_types = set()
# Iterate through all entities in the model and collect their types
for entity in ifc_model:
    entity_types.add(entity.is_a())

print(sorted(entity_types)[:7])

['IfcApplication', 'IfcAxis2Placement3D', 'IfcBeam', 'IfcBeamType', 'IfcBuilding', 'IfcBuildingStorey', 'IfcCartesianPoint']


In [22]:
len(entity_types)

59

In [23]:
# Print all unique entity types
total = 0
size_set = set()
for entity_type in sorted(entity_types):
    print(entity_type + " " + str(len(ifc_model.by_type(entity_type))))
    total += len(ifc_model.by_type(entity_type))
    for i in ifc_model.by_type(entity_type):
        size_set.add(len(i.__dict__))

IfcApplication 1
IfcAxis2Placement3D 284
IfcBeam 45
IfcBeamType 4
IfcBuilding 1
IfcBuildingStorey 1
IfcCartesianPoint 425
IfcClosedShell 8
IfcColourRgb 6
IfcColumn 28
IfcColumnType 2
IfcConversionBasedUnit 4
IfcDimensionalExponents 4
IfcDirection 5
IfcElementAssembly 281
IfcElementQuantity 15
IfcFace 80
IfcFaceOuterBound 80
IfcFacetedBrep 8
IfcFooting 28
IfcGeometricCurveSet 3
IfcGeometricRepresentationContext 4
IfcGeometricRepresentationSubContext 3
IfcGrid 3
IfcGridAxis 27
IfcLocalPlacement 568
IfcMaterial 3
IfcMeasureWithUnit 4
IfcOrganization 1
IfcOwnerHistory 2
IfcPerson 1
IfcPersonAndOrganization 1
IfcPolyLoop 80
IfcPolyline 9
IfcPostalAddress 1
IfcPresentationLayerAssignment 9
IfcPresentationStyleAssignment 6
IfcProductDefinitionShape 284
IfcProject 1
IfcPropertySet 137
IfcPropertySingleValue 179
IfcQuantityArea 9
IfcQuantityLength 11
IfcQuantityVolume 9
IfcQuantityWeight 8
IfcRelAggregates 284
IfcRelAssociatesMaterial 3
IfcRelContainedInSpatialStructure 2
IfcRelDefinesByPropert

In [13]:
size_set

{3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 16}

In [16]:
# Get all entities in the model
all_entities = ifc_model.by_type("IfcProduct")  # Or use "IfcRoot" for broader counting

# Print the number of entities
print("Number of entities:", len(all_entities))

Number of entities: 568


In [24]:
all_entities

[#106=IfcBeam('0ZWISPgWb95RvI9c59d4m6',#45,'BEAM','RCL300x360-500x150',$,#105,#102,'B-0(?)'),
 #142=IfcBeam('3bqcsHjbz0S9q0Nogf3XcX',#45,'BEAM','RCL300x360-500x150',$,#141,#138,'B-0(?)'),
 #152=IfcBeam('24FXDPHCr1Ne5rAky$ZIlz',#45,'BEAM','RCL300x360-500x150',$,#151,#148,'B-0(?)'),
 #197=IfcBeam('29IRNLNV96chHhmz$Wy4Z_',#45,'BEAM','RCDL300x360-500x150',$,#196,#193,'B-0(?)'),
 #209=IfcBeam('21ta32ne59geQqv_JreKYa',#45,'BEAM','RCDL300x360-500x150',$,#208,#205,'B-0(?)'),
 #217=IfcBeam('1rSHaT$P1EjebkAHWWtONU',#45,'BEAM','RCDL300x360-500x150',$,#216,#213,'B-0(?)'),
 #227=IfcBeam('2WKzzdERjF1hbShgl7ugzI',#45,'BEAM','RCDL300x360-500x150',$,#226,#223,'B-0(?)'),
 #237=IfcBeam('0IcN3QO0T9O9Yfx2gB7ghB',#45,'BEAM','RCDL300x360-500x150',$,#236,#233,'B-0(?)'),
 #247=IfcBeam('006TdrAbP5MwdAzVgPswRq',#45,'BEAM','RCDL300x360-500x150',$,#246,#243,'B-0(?)'),
 #258=IfcBeam('3zQXjqL9vBiv$PKxeLbPkN',#45,'BEAM','RCL300x360-500x150',$,#257,#254,'B-0(?)'),
 #270=IfcBeam('3W2Mc6hrT1fOJg1h1UVIV$',#45,'BEAM','RCL

In [25]:
import ifcopenshell
from ifcopenshell.geom import create_shape
from ifcopenshell import util

# Load the IFC model
#ifc_model = ifcopenshell.open('path/to/your/file.ifc')

# Set up geometry settings
settings = ifcopenshell.geom.settings()

# Function to get the location of an object (position and orientation)
def get_location(entity):
    # Check if the entity has a Local Placement
    if entity.is_a('IfcProduct'):
        placement = entity.ObjectPlacement
        if placement and placement.is_a('IfcLocalPlacement'):
            # Extract the location (position) and orientation (rotation)
            placement_location = placement.RelativePlacement.Location
            return placement_location
    return None

# Function to extract geometry and location for each product (object)
for entity in ifc_model.by_type('IfcProduct'):
    try:
        # Get the geometry for the product (e.g., wall, door, etc.)
        shape = create_shape(settings, entity)
        geometry = shape.geometry
        
        # Get the location of the entity
        location = get_location(entity)

        # Print geometry and location information (for debugging or processing)
        print(f"Entity: {entity}")
        print(f"Geometry: {geometry}")  # This will be the raw geometry data (can be further processed)
        
        if location:
            print(f"Location: {location}")
        else:
            print("No location found.")
        
        print("-" * 50)  # Separator for readability
    except Exception as e:
        print(f"Error processing {entity}: {e}")

Entity: #106=IfcBeam('0ZWISPgWb95RvI9c59d4m6',#45,'BEAM','RCL300x360-500x150',$,#105,#102,'B-0(?)')
Geometry: <ifcopenshell.ifcopenshell_wrapper.Triangulation; proxy of <Swig Object of type 'IfcGeom::Representation::Triangulation *' at 0x769ab4dec7b0> >
Location: #103=IfcCartesianPoint((36000.,12000.,7020.))
--------------------------------------------------
Entity: #142=IfcBeam('3bqcsHjbz0S9q0Nogf3XcX',#45,'BEAM','RCL300x360-500x150',$,#141,#138,'B-0(?)')
Geometry: <ifcopenshell.ifcopenshell_wrapper.Triangulation; proxy of <Swig Object of type 'IfcGeom::Representation::Triangulation *' at 0x769ac80aec10> >
Location: #139=IfcCartesianPoint((36000.,6000.,7020.))
--------------------------------------------------
Entity: #152=IfcBeam('24FXDPHCr1Ne5rAky$ZIlz',#45,'BEAM','RCL300x360-500x150',$,#151,#148,'B-0(?)')
Geometry: <ifcopenshell.ifcopenshell_wrapper.Triangulation; proxy of <Swig Object of type 'IfcGeom::Representation::Triangulation *' at 0x769ac2b93600> >
Location: #139=IfcCartesi

In [26]:
# Retrieve the geometry (triangulated mesh) and location for an entity
for entity in ifc_model.by_type('IfcProduct'):
    try:
        # Create shape for the entity
        shape = create_shape(settings, entity)
        geometry = shape.geometry

        # Get location (position)
        location = get_location(entity)
        if location:
            position = location.Coordinates
            print(f"Entity: {entity.GlobalId} Location: {position}")
        
    except Exception as e:
        print(f"Error processing {entity}: {e}")


Entity: 0ZWISPgWb95RvI9c59d4m6 Location: (36000.0, 12000.0, 7020.0)
Entity: 3bqcsHjbz0S9q0Nogf3XcX Location: (36000.0, 6000.0, 7020.0)
Entity: 24FXDPHCr1Ne5rAky$ZIlz Location: (36000.0, 6000.0, 7020.0)
Entity: 29IRNLNV96chHhmz$Wy4Z_ Location: (30000.0, 12000.0, 7020.0)
Entity: 21ta32ne59geQqv_JreKYa Location: (30000.0, 6000.0, 7020.0)
Entity: 1rSHaT$P1EjebkAHWWtONU Location: (30000.0, 0.0, 7020.0)
Entity: 2WKzzdERjF1hbShgl7ugzI Location: (24000.0, 12000.0, 7020.0)
Entity: 0IcN3QO0T9O9Yfx2gB7ghB Location: (24000.0, 6000.0, 7020.0)
Entity: 006TdrAbP5MwdAzVgPswRq Location: (24000.0, 0.0, 7020.0)
Entity: 3zQXjqL9vBiv$PKxeLbPkN Location: (36000.0, 12000.0, 3420.0)
Entity: 3W2Mc6hrT1fOJg1h1UVIV$ Location: (36000.0, 6000.0, 3420.0)
Entity: 33IOfyxFbADuxv9Wi4Gwyh Location: (36000.0, 6000.0, 3420.0)
Entity: 2DjvkcfBrCIuwJLADdizpx Location: (30000.0, 12000.0, 3420.0)
Entity: 0ah3Vsjgf3BhBowSOFI_fN Location: (30000.0, 6000.0, 3420.0)
Entity: 2Ctoiy41XAdAdrJNGIElwa Location: (30000.0, 0.0, 3420.0)

In [27]:
# Debugging geometry attributes
print(f"Geometry attributes: {geometry.__dict__}")

Geometry attributes: {'this': <Swig Object of type 'IfcGeom::Representation::Triangulation *' at 0x769ab4c1a4f0>}


In [29]:
import ifcopenshell
import ifcopenshell.geom
import ifcopenshell.util.shape

ifc_file = ifcopenshell.open('DummyModel.ifc')
element = ifc_file.by_type('IfcColumn')[0]

settings = ifcopenshell.geom.settings()
shape = ifcopenshell.geom.create_shape(settings, element)

# The GUID of the element we processed
print("GUID ", shape.guid)

# The ID of the element we processed
print("id ", shape.id)

# The element we are processing
print("Element", ifc_file.by_guid(shape.guid))

# A unique geometry ID, useful to check whether or not two geometries are
# identical for caching and reuse. The naming scheme is:
# IfcShapeRepresentation.id{-layerset-LayerSet.id}{-material-Material.id}{-openings-[Opening n.id ...]}{-world-coords}
print(shape.geometry.id)

# A 4x4 matrix representing the location and rotation of the element, in the form:
# [ [ x_x, y_x, z_x, x   ]
#   [ x_y, y_y, z_y, y   ]
#   [ x_z, y_z, z_z, z   ]
#   [ 0.0, 0.0, 0.0, 1.0 ] ]
# The position is given by the last column: (x, y, z)
# The rotation is described by the first three columns, by explicitly specifying the local X, Y, Z axes.
# The first column is a normalised vector of the local X axis: (x_x, x_y, x_z)
# The second column is a normalised vector of the local Y axis: (y_x, y_y, y_z)
# The third column is a normalised vector of the local Z axis: (z_x, z_y, z_z)
# The axes follow a right-handed coordinate system.
# Objects are never scaled, so the scale factor of the matrix is always 1.
matrix = shape.transformation.matrix

# For convenience, you might want the matrix as a nested numpy array, so you can do matrix math.
matrix = ifcopenshell.util.shape.get_shape_matrix(shape)

# You can also extract the XYZ location of the matrix.
location = matrix[:,3][0:3]

# X Y Z of vertices in flattened list e.g. [v1x, v1y, v1z, v2x, v2y, v2z, ...]
# These vertices are local relative to the shape's transformation matrix.
verts = shape.geometry.verts

# Indices of vertices per edge e.g. [e1v1, e1v2, e2v1, e2v2, ...]
# If the geometry is mesh-like, edges contain the original edges.
# These may be quads or ngons and not necessarily triangles.
edges = shape.geometry.edges

# Indices of vertices per triangle face e.g. [f1v1, f1v2, f1v3, f2v1, f2v2, f2v3, ...]
# Note that faces are always triangles.
faces = shape.geometry.faces

# Since the lists are flattened, you may prefer to group them like so depending on your geometry kernel
# A nested numpy array e.g. [[v1x, v1y, v1z], [v2x, v2y, v2z], ...]
grouped_verts = ifcopenshell.util.shape.get_vertices(shape.geometry)
# A nested numpy array e.g. [[e1v1, e1v2], [e2v1, e2v2], ...]
grouped_edges = ifcopenshell.util.shape.get_edges(shape.geometry)
# A nested numpy array e.g. [[f1v1, f1v2, f1v3], [f2v1, f2v2, f2v3], ...]
grouped_faces = ifcopenshell.util.shape.get_faces(shape.geometry)

# A list of styles that are relevant to this shape
styles = shape.geometry.materials
print(styles)

for style in styles:
    # Each style is named after the entity class if a default
    # material is applied. Otherwise, it is named "surface-style-{SurfaceStyle.name}"
    # All non-alphanumeric characters are replaced with a "-".
    #print(style.original_name())

    # A more human readable name
    #print(style.name)

    # Each style may have diffuse colour RGB codes
    #if style.has_diffuse:
    #    print(style.diffuse)

    # Each style may have transparency data
    if style.has_transparency:
        print(style.transparency)

# Indices of material applied per triangle face e.g. [f1m, f2m, ...]
material_ids = shape.geometry.material_ids

# IDs representation item per triangle face e.g. [f1i, f2i, ...]
item_ids = shape.geometry.item_ids

GUID  3BCWkUnn5CcQHYl8jbVpYV
id  1272
Element #1272=IfcColumn('3BCWkUnn5CcQHYl8jbVpYV',#45,'COLUMN','400x400',$,#1271,#1268,'C-0(?)')
1267
(style
     name IfcSurfaceStyleRendering-1235
     diffuse
            colour 0.956863 0.694118 0
     specular
             colour 0.00390625 0.00390625 0.00390625
,)
0.0


Element #1272=IfcColumn('3BCWkUnn5CcQHYl8jbVpYV',#45,'COLUMN','400x400',$,#1272,#1268,'C-0(?)')
IfcColumn: Indicates the type of IFC entity.
'3BCWkUnn5CcQHYl8jbVpYV': This could be the globally unique identifier (GUID) for the column.
#45: Likely refers to an IFC label or an attribute such as the owner history.
'COLUMN': A name or description given to the column.
'400x400': Could be the profile size or a nominal dimension of the column (e.g., 400 mm x 400 mm).
$: Represents an undefined or null value in IFC.
#1271, #1268: These numbers probably reference other IFC entities (such as geometric representations, placement, or relationships) within the same file.
'C-0(?)': This may be an indication of a tag, label, or type designation for the column.

In [30]:
material_ids

(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)

In [31]:
def print_by_ids(ids):
    for i in ids:
        print(ifc_file.by_id(i))

In [45]:
print(set(item_ids))
print_by_ids([1272,1271,1268,1267,1265,1264])

{1265}
#1272=IfcColumn('3BCWkUnn5CcQHYl8jbVpYV',#45,'COLUMN','400x400',$,#1271,#1268,'C-0(?)')
#1271=IfcLocalPlacement(#1225,#1270)
#1268=IfcProductDefinitionShape($,$,(#1267))
#1267=IfcShapeRepresentation(#12,'Body','Brep',(#1265))
#1265=IfcFacetedBrep(#1264)
#1264=IfcClosedShell((#1244,#1249,#1254,#1257,#1260,#1263))


In [52]:
print_by_ids([1225,1270,43,10,1269])

#1225=IfcLocalPlacement(#43,#10)
#1270=IfcAxis2Placement3D(#1269,#8,#9)
#43=IfcLocalPlacement(#41,#10)
#10=IfcAxis2Placement3D(#6,#9,#7)
#1269=IfcCartesianPoint((36000.,0.,0.))


In [41]:
print_by_ids([1244,1243,1242])

#1244=IfcFace((#1243))
#1243=IfcFaceOuterBound(#1242,.T.)
#1242=IfcPolyLoop((#1238,#1239,#1240,#1241))


In [44]:
print_by_ids([1238,1239,1240,1241])

#1238=IfcCartesianPoint((0.,200.,-200.))
#1239=IfcCartesianPoint((0.,200.,200.))
#1240=IfcCartesianPoint((7200.,200.,200.))
#1241=IfcCartesianPoint((7200.,200.,-200.))


In [56]:
import multiprocessing
import ifcopenshell
import ifcopenshell.geom

tree = ifcopenshell.geom.tree()
settings = ifcopenshell.geom.settings()
iterator = ifcopenshell.geom.iterator(settings, ifc_file, multiprocessing.cpu_count())
if iterator.initialize():
    while True:
        # Use triangulation to build a BVH tree
        tree.add_element(iterator.get())

        # Alternatively, use this code to build an unbalanced binary tree
        # tree.add_element(iterator.get_native())

        if not iterator.next():
            break

In [58]:
model = ifc_file
clashes = tree.clash_intersection_many(
    #group_a_elements, # e.g. from model.by_type("IfcWall")
    #group_b_elements, # Group b can be the same as group a if you want to clash within a single set
    model.by_type("IfcColumn"),
    model.by_type("IfcBeam"),
    tolerance=0.002, # Any protrusions less than 2mm are ignored
    check_all=True, # Keep on checking all potential intersections to find a worst case protrusion distance
)

for clash in clashes:
    # Get the two elements that clash and their metadata
    element1 = clash.a
    element2 = clash.b
    a_global_id = element1.get_argument(0)
    b_global_id = element2.get_argument(0)
    a_ifc_class = element1.is_a()
    b_ifc_class = element2.is_a()
    a_name = element1.get_argument(2)
    b_name = element2.get_argument(2)

    # Potential clash types that can be detected are protrusions, pierces, and collisions
    clash_type = ["protrusion", "pierce", "collision", "clearance"][clash.clash_type],

    # P1 and P2 represents two XYZ coordinates. The meaning of the coordinate depends on the clash type.
    p1 = list(clash.p1)
    p2 = list(clash.p2)

    # This represents the protrusion or piercing distance in meters.
    # It is also the distance between P1 and P2.
    distance = clash.distance

In [60]:
len(clashes)

90

In [68]:
12*7

84

In [66]:
for clash in clashes:
    # Existing code to extract clash details
    element1 = clash.a
    element2 = clash.b

    # Retrieve geometry data (pseudo-code)
   # geom1 = element1.get_geometry()  # Replace with actual method to access geometry
    #geom2 = element2.get_geometry()  # Replace with actual method to access geometry

    # Analyze or visualize the clash
    # Use visualization libraries or geometry processing to highlight `p1` and `p2`
    
    # Print or process the coordinates of the clash
    print(f"Clash detected between {element1.is_a()} and {element2.is_a()}:")
    print(f"  Closest points: {p1} and {p2}")
    print(f"  Distance: {clash.distance:.3f} meters")

Clash detected between IfcBeam and IfcColumn:
  Closest points: [12.080663134431742, 0.15500000000000003, 3.5866578852537714] and [12.08047876753282, 0.1395, 3.587325241493538]
  Distance: 0.200 meters
Clash detected between IfcBeam and IfcColumn:
  Closest points: [12.080663134431742, 0.15500000000000003, 3.5866578852537714] and [12.08047876753282, 0.1395, 3.587325241493538]
  Distance: 0.200 meters
Clash detected between IfcBeam and IfcColumn:
  Closest points: [12.080663134431742, 0.15500000000000003, 3.5866578852537714] and [12.08047876753282, 0.1395, 3.587325241493538]
  Distance: 0.200 meters
Clash detected between IfcBeam and IfcColumn:
  Closest points: [12.080663134431742, 0.15500000000000003, 3.5866578852537714] and [12.08047876753282, 0.1395, 3.587325241493538]
  Distance: 0.200 meters
Clash detected between IfcBeam and IfcColumn:
  Closest points: [12.080663134431742, 0.15500000000000003, 3.5866578852537714] and [12.08047876753282, 0.1395, 3.587325241493538]
  Distance: 0.2

clashes

In [53]:
import ifcopenshell

# Load the IFC file
ifc_file = ifcopenshell.open('DummyModel.ifc')

# Find the IfcColumn entity by its unique identifier or type
column = ifc_file.by_type('IfcColumn')[0]

# Traverse related entities to get the IfcFacetedBrep and IfcClosedShell
shape = column.Representation.Representations[0]
brep = shape.Items[0]
shell = brep.Outer

# Extract coordinates from the IfcClosedShell
points = set()
for face in shell.CfsFaces:
    for bound in face.Bounds:
        loop = bound.Bound
        for vertex in loop.Polygon:
            points.add(vertex.Coordinates)

# Find min and max for each axis
min_x = min(p[0] for p in points)
max_x = max(p[0] for p in points)
min_y = min(p[1] for p in points)
max_y = max(p[1] for p in points)
min_z = min(p[2] for p in points)
max_z = max(p[2] for p in points)

# Calculate dimensions
width = max_x - min_x
depth = max_y - min_y
height = max_z - min_z

print(points)
print(f'Width: {width}, Depth: {depth}, Height: {height}')

{(7200.0, -200.0, -200.0), (0.0, 200.0, 200.0), (7200.0, 200.0, 200.0), (0.0, -200.0, 200.0), (7200.0, 200.0, -200.0), (0.0, 200.0, -200.0), (7200.0, -200.0, 200.0), (0.0, -200.0, -200.0)}
Width: 7200.0, Depth: 400.0, Height: 400.0


In [2]:
import ifcopenshell

def get_ifc_arbitrary_closed_profile_data(ifc_file_path):
    """
    Extracts all data related to IfcArbitraryClosedProfileDef entities from an IFC file.

    Parameters:
    ifc_file_path (str): Path to the IFC file.

    Returns:
    list: A list of dictionaries containing data about each IfcArbitraryClosedProfileDef entity.
    """
    # Open the IFC file
    ifc_file = ifcopenshell.open(ifc_file_path)
    
    # Find all IfcArbitraryClosedProfileDef entities
    profiles = ifc_file.by_type('IfcArbitraryClosedProfileDef')
    
    # Extract data for each entity
    profile_data = []
    for profile in profiles:
        data = {
            #'GlobalId': profile.GlobalId,
            'Name': profile.Name,
            'OuterCurve': profile.OuterCurve,  # Reference to the defining curve
            'Description': profile.Description,
        }
        profile_data.append(data)
    
    return profile_data

# Example usage
ifc_path = 'AC20-FZK-Haus1.ifc'
profile_info = get_ifc_arbitrary_closed_profile_data(ifc_path)

# Print profile information
for profile in profile_info:
    print(profilifc_path = 'AC20-FZK-Haus1.ifc'e)


AttributeError: entity instance of type 'IFC4.IfcArbitraryClosedProfileDef' has no attribute 'Name'

In [4]:
ifc_path = 'AC20-FZK-Haus1.ifc'
ifc_file = ifcopenshell.open(ifc_path)
profiles = ifc_file.by_type('IfcArbitraryClosedProfileDef')

In [8]:
profiles[0].OuterCurve

#14992=IfcPolyline((#14984,#14986,#14988,#14990,#14984))

In [9]:
ifc_file.by_id(14984)

#14984=IfcCartesianPoint((0.,-0.24))